### ISSUE TITLE
feature request: support tmux

### ISSUE THREAD

**Issue by epheien** [mil-ad/kitcat#2]
I know `image.nvim` (a nvim plugin) and `yazi` support kitty graphic protocal in tmux.

**Comment by mil-ad** [comment]
yeah I think tmux provides a passthrough mechanism for escape sequences. It's on top of my list of things to add.

**Comment by epheien** [comment]
This is a simple implement
```python
def escape(sequence):
    if 'TMUX' in os.environ:
        return "\x1bPtmux;" + sequence.replace("\x1b", "\x1b\x1b") + "\x1b\\"
    else:
        return sequence

...

    sys.stdout.write(escape(f"\033_Gm={'1' if more_data else '0'},a=T,f=100;{first_chunk}\033\\"))
```

But after the picture was displayed, the prompt did not follow closely after the picture.

<img width="952" alt="Xnip2024-11-21_19-30-05" src="https://github.com/user-attachments/assets/da3dbfc0-97ad-4831-aca1-2414c88caf49">

**Comment by mil-ad** [comment]
Thanks this is useful. I think we need to find figure height in pixels and tty's pixels-per-line (see [here](https://sw.kovidgoyal.net/kitty/graphics-protocol/#getting-the-window-size)) and manually issue the correct number of `\n`s to move the cursor.

**Comment by mil-ad** [comment]
I'll set up a branch to hack something together

**Comment by mil-ad** [comment]
@epheien I have started adding tmux support in #4. It does work for me in kitty but not in VS Code. I don't have a Mac at the moment to see if it works in iTerm or not. 

The PR should handle the cursor after displaying the image but the problem is that if you try scrolling in tmux the image doesn't move.

**Comment by epheien** [comment]
<img width="816" alt="Xnip2024-11-22_20-09-05" src="https://github.com/user-attachments/assets/ef36eb54-4169-45a6-a657-1338ac75b058">

Hello, I test on macOS 12.7.6, ssh to ubuntu 22.04, tmux 3.4, iTerm2, It works.
And if I try scrolling in tmux or run `clear`, image will disappear. It's much better than not moving than Kitty.

**Comment by mil-ad** [comment]
Nice, thanks for testing! I'll make a release today. 

Wez handles this the best it seems. I raised an an [issue](https://github.com/kovidgoyal/kitty/issues/8014) for Kitty a few weeks ago but 🤷🏼‍♂️

**Comment by mil-ad** [comment]
Made v1.2.0 release on pypi
